services:
  back:
    build: ./backend/
    container_name: backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "3000:3000" 
    volumes:
      - ./backend:/app
      - /app/node_modules

  front:
    build: ./frontend/
    container_name: frontend
    networks:
      - app-network
    ports:
      - "4200:4200" 
    volumes:
    - ./frontend:/app
    - /app/node_modules

  db:
    image: mysql
    container_name: mysql
    restart: always
    env_file:
      - ./env/mysql.env 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge


